eclipse-pass/pass-authz

pass-authz-core/pom.xml, pass-authz-filters/pom.xml, pass-authz-integration/pom.xml, pass-authz-integration/src/test/java/org/dataconservancy/pass/authz/ShibAuthUserServiceIT.java, pass-authz-integration/src/test/resources/docker/Dockerfile, pass-user-service/pom.xml, pom.xml
Question for reviewer: does this need to change?
https://github.com/OA-PASS/pass-authz/blob/b5da1117faecc7a1dbb3ef9227fc45c16c29322c/pass-authz-core/src/main/java/org/dataconservancy/pass/authz/AuthRolesProvider.java#L52
=> Replace example.org in context URL with oapass.org

pass-authz-acl/pom.xml, pass-authz-core/pom.xml, pass-authz-filters/pom.xml, pass-authz-integration/pom.xml, pass-authz-integration/src/test/java/org/dataconservancy/pass/authz/ShibAuthUserServiceIT.java, pass-authz-tools/pom.xml, pass-user-service/pom.xml, pass-user-service/src/main/java/org/dataconservancy/pass/authz/service/user/UserServlet.java, pom.xml
This is workaround for an issue where Ember does not receive all of the properties of a 401 error, but does receive the response body for some reason. This gives Ember something to use in order to determine whether a 401 page should be displayed.
Incremented version to `0.1.1-SNAPSHOT` for release
=> Add body to 401 response, increment version 

pass-authz-acl/src/main/java/org/dataconservancy/pass/authz/acl/PolicyEngine.java, pass-authz-acl/src/main/resources/containers.yml, pass-authz-integration/src/test/java/org/dataconservancy/pass/authz/PassAuthzIT.java, pass-authz-integration/src/test/java/org/dataconservancy/pass/authz/PolicyListenerIT.java, pass-authz-tools/src/main/java/org/dataconservancy/pass/authz/tools/AuthzListener.java, pass-authz-tools/src/main/java/org/dataconservancy/pass/authz/tools/main/AuthzListenerService.java, pass-authz-tools/src/main/java/org/dataconservancy/pass/authz/tools/main/PermissionsUpdater.java
Updates the `PolicyEngine` and ITs so that grants do _not_ have individual ACLs.   The end result is that grants retain default permissions (readable by submitters, admins, writable by backend only).
Individual ACLs are still enabled for submissions, such that:
* Everybody (grant, admin) can always read every submission
* Any submitter can create a submission
* A submission can only be modified by the User associated with it, and only if it has not been designated `submitted=true`
* A submission with `submitted = true` is writable only by PASS backend services
=> Remove individual ACLs for grants

pass-authz-core/src/main/java/org/dataconservancy/pass/authz/AuthUserProvider.java, pass-authz-core/src/main/java/org/dataconservancy/pass/authz/ExpiringLRUCache.java, pass-authz-core/src/main/java/org/dataconservancy/pass/authz/ShibAuthUserProvider.java, pass-authz-core/src/test/java/org/dataconservancy/pass/authz/ExpiringLRUCacheTest.java, pass-authz-core/src/test/java/org/dataconservancy/pass/authz/ShibAuthUserProviderTest.java, pass-authz-core/src/test/resources/logback-test.xml, pass-authz-integration/src/test/java/org/dataconservancy/pass/authz/ShibAuthUserServiceIT.java, pass-user-service/src/main/java/org/dataconservancy/pass/authz/service/user/UserServlet.java, pass-user-service/src/test/java/org/dataconservancy/pass/authz/service/user/UserServletTest.java
`ExpiringLRUCache` provides a critical section for dong some 'computation' of a cached value if it is not already present in the cache.  At the moment, as far as the User service is concerned, lookup of Users occurs in that critical section, but creation does not.  This refactors the situation so that the lookup _and_ creation occurs in the critical section, and results are cached.  This eliminates the need to search for users by their `localKey` immediately after they are created, which makes the process immune to normal async lags in indexing.
Also removes the retry logic for lookup of users, and expands tests
Resolves #33
=> Fix duplicate user by creating Users in a critical section

pass-authz-integration/src/test/java/org/dataconservancy/pass/authz/ShibAuthUserServiceIT.java, pass-user-service/src/main/java/org/dataconservancy/pass/authz/service/user/UserServlet.java, pass-user-service/src/test/java/org/dataconservancy/pass/authz/service/user/UserServletTest.java
* Uses the JSON adapter from the PASS client for serialization, rather than directly using Jackson
* Enhances ITs to look for the proper JSON-LD User format in responses.
Resolves #36
=> Ensure the user service responds with a User in JSON-LD

pass-authz-core/src/main/java/org/dataconservancy/pass/authz/AuthUser.java, pass-authz-core/src/main/java/org/dataconservancy/pass/authz/ShibAuthUserProvider.java, pass-authz-core/src/test/java/org/dataconservancy/pass/authz/ShibAuthUserProviderTest.java, pass-authz-integration/src/test/java/org/dataconservancy/pass/authz/ShibAuthUserServiceIT.java, pass-user-service/src/main/java/org/dataconservancy/pass/authz/service/user/UserServlet.java, pass-user-service/src/test/java/org/dataconservancy/pass/authz/service/user/UserServletTest.java
Previously, the User service compared the contents of the `User` resource to the shib headers as a last step in User service processing, updating the User if it needed to.  It performed this on every request.  A consequence of this is is (a) many useless checks, and (b) the possibility of conflicts if the "retrieve User" and "update User" stages of two separate threads overlap, for the same user.  This does happen occasionally in real life, due to the fact that Ember calls the User service twice in a row when logging in.
This PR addresses the above concerns by moving User updating process to the LRUCache critical section.   This has the additional implication that updates to User resources so that they sync with shib attributes only occurs on cache misses.  Once in the cache, the syncing …
=> Move User updating to the critical section

pass-authz-acl/src/main/java/org/dataconservancy/pass/authz/acl/PolicyEngine.java, pass-authz-acl/src/test/java/org/dataconservancy/pass/authz/acl/PolicyEngineTest.java, pass-authz-integration/src/test/java/org/dataconservancy/pass/authz/PolicyListenerIT.java, pass-authz-listener/src/main/java/org/dataconservancy/pass/authz/listener/AuthzListener.java
Updates the authz listener to update ACLS to assure that submissionEvents are immutable.
Resolves #46
=> Add immutability to submissionEvents, and test

pass-authz-acl/src/main/java/org/dataconservancy/pass/authz/acl/PolicyEngine.java, pass-authz-acl/src/test/java/org/dataconservancy/pass/authz/acl/PolicyEngineTest.java
Use the new `SubmissionStatus#isSubmitted()` as the primary means to determine if a submission is read-only.  If that is undefined, fall back to the `submitted` boolean
Resolves #47
=> SubmissionStatus determines if submission is editable

pass-user-service/src/main/java/org/dataconservancy/pass/authz/service/user/UserServlet.java, pom.xml
This will keep the cached `User` values clean, allowing `AuthRolesProvider` to properly look up users using the correct URIs.
Resolves #63
=> Use defensive copy of User when updating response URIs

pass-authz-acl/src/main/java/org/dataconservancy/pass/authz/acl/PolicyEngine.java, pass-authz-acl/src/test/java/org/dataconservancy/pass/authz/acl/PolicyEngineTest.java
Currently, a `cancelled` submission is not treated as a terminal state.  However, the documentation suggests that cancelled submissions ought to be immutable.  This adds a special case for making cancelled submissions immutable, and updates the tests.
Resolves #59
=> Handle cancelled submission immutability as a special case

pass-authz-tools/pom.xml
This was a leftover from before a refactoring, and is no longer used here.  The real listener artifact is created in pass-authz-listener
=> Remove unused listener artifact in pom

pass-authz-integration/src/test/java/org/dataconservancy/pass/authz/UserServiceIT.java, pass-user-service/src/main/java/org/dataconservancy/pass/authz/service/user/TokenService.java, pass-user-service/src/main/java/org/dataconservancy/pass/authz/service/user/UserServlet.java, pass-user-service/src/test/java/org/dataconservancy/pass/authz/service/user/TokenServiceTest.java, pass-user-service/src/test/java/org/dataconservancy/pass/authz/service/user/UserServletTest.java, pom.xml
Previously, the user token encoded the submitter URI and a placeholder
URI.  Since emmber cannot deal with the placeholder, the model was
updated to add fields submitterName and submitterEmail, which
essentially serve as single-purpose placeholders.  Thus PR adappts the
user token algorithm to these changes.
Note:  The new mechanism is less general, and hard-wires substitution so
that it can _only_ apply to submitters (e.g. it would not be possible to
invite proxy users without a data model change).
Resolves #68
=> Use submitterEmail() algorithm for user tokens

README.md, pass-authz-tools/src/main/java/org/dataconservancy/pass/authz/tools/main/PermissionsUpdater.java
* Iterates permissions of both Submissions and SubmissionEvents now
* Adds a system property `type` that can be used for specifying a single type to act on.
* doc updates
Resolves #60
=> Support submissionEvents and selecting type in CLI app

pass-authz-integration/src/test/java/org/dataconservancy/pass/authz/UserServiceIT.java, pass-authz-integration/src/test/resources/docker/Dockerfile, pass-authz-usertoken/src/main/java/org/dataconservancy/pass/authz/usertoken/Token.java, pass-user-service/src/main/java/org/dataconservancy/pass/authz/service/user/TokenService.java, pass-user-service/src/main/java/org/dataconservancy/pass/authz/service/user/UserServlet.java
Tokens are used for enacting permissions changes to submissions, and have nothing to do with creating or updating users.  This conflation lead to the incorrect solution of invalidating the cache in order to
enact a token.  
Instead, this PR explores separating out the token logic, and protecting it by its own cache so that each token is only enacted once in the face of concurrent requests
=> Move token logic outside of the user generator

pass-authz-core/src/main/java/org/dataconservancy/pass/authz/AuthUser.java, pass-authz-core/src/main/java/org/dataconservancy/pass/authz/ShibAuthUserProvider.java, pass-user-service/src/main/java/org/dataconservancy/pass/authz/service/user/UserServlet.java, pass-user-service/src/test/java/org/dataconservancy/pass/authz/service/user/UserServletTest.java
Update pass-user-service to include given name and surname when creating or updating User resources
- Add ShibAuthUser support for reading the Shibboleth headers 'Givenname' and 'Surname' respectively
- Add givenName and surname as fields on AuthUser
- Update UserServlet to set User.firstName and User.lastName from the AuthUser.givenName and AuthUser.surname
- Update tests
=> Include first and last name when creating or updating User resources

pass-authz-integration/pom.xml
Support builds of pass-authz on machines running `docker-machine`.
This PR should be tested by someone who does _not_ use `docker-machine` (I've already tested it on my computer which _does_ use `docker-machine`).
To test, simply check out this PR and run `mvn clean install`.  A successful build indicates that this PR is working.
=> Update to pass-authz-integration to support builds on docker-machine.

.travis.yml, README.md, pass-authz-tools/src/main/java/org/dataconservancy/pass/authz/tools/main/Const.java, pass-authz-tools/src/main/java/org/dataconservancy/pass/authz/tools/main/ContainerPermissions.java, pass-authz-tools/src/main/java/org/dataconservancy/pass/authz/tools/main/PermissionsUpdater.java
Allow for the base URI for roles to be set via a system property or env var (`pass.authz.rolebase`, `PASS_AUTHZ_ROLEBASE`) when updating container or resource ACLs using `pass-authz-tools`.
=> Update pass-authz-tools to use an externally-defined role base

.travis.yml, pass-authz-core/src/main/java/org/dataconservancy/pass/authz/ShibAuthUserProvider.java
Replaces `hopkinsid` identifier type with `unique-id`.  Replaces `jhed` identifier type with `eppn`.
Users will get created with locator ids that no longer have types that refer to hopkins, e.g.:
```json
{
"@type" : "User",
"username" : "incomplete-nih-user@harvard.edu",
"firstName" : "Incomplete",
"middleName" : null,
"lastName" : "Nihuser",
"displayName" : "Incomplete Nihuser",
"email" : "incompletenihuser@harvard.edu",
"affiliation" : null,
"locatorIds" : [ "harvard.edu:eppn:incomplete-nih-user", "harvard.edu:employeeid:00023666", "harvard.edu:unique-id:SDH72F" ],
"orcidId" : null,
"roles" : [ "submitter" ],
"@id" : "https://pass.local/fcrepo/rest/users/2e/67/a3/cb/2e67a3cb-1200-497b-ba0e-2c91a5d562a7",
"@context" : "https://oa-pass.github.io/pass-data-model/src/main/resources/context-3 …
```
=> Remove hopkins-isms from the locator id types

.github/workflows/ci.yml, .github/workflows/parent-pom-workaround.yml
Added workaround that'll be needed until `eclipse-pass-parent/0.0.1-SNAPSHOT` is published.
=> Added parent pom workaround (eclipse-pass-parent/0.0.1-SNAPSHOT)

.github/workflows/ci.yml, pom.xml
* Add a compiler argument to the test runner to ignore illegal access exceptions
* The `powermock` library used in some tests in this repository seems to have never been updated to support Java 11 properly. This workaround explicitly ignores the new exceptions.
=> Add workaround to force Java 11 compatibility
